openapi: 3.0.1
info:
  title: Tic-Tac-Toe-app-api specification
  version: v0
servers:
  - url: http://localhost:5678
    description: Generated server url
paths:
  /tictactoe/startNewGame:
    post:
      tags:
        - tic-tac-toe-controller
      operationId: startNewGame
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewGameInfo'
  /tictactoe-players/info:
    get:
      tags:
        - tic-tac-toe-controller
      operationId: getPlayersInfo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
  /tictactoe/playerTurn:
    patch:
      tags:
        - tic-tac-toe-controller
      operationId: playerTurn
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TurnRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TurnResponse'                  

components:
  schemas:
    NewGameInfo:
      type: object
      properties:
        message:
          type: string
        gameboard:
          type: object
          additionalProperties:
            type: string
    Player:
      type: object
      properties:
        id:
          type: string
        description:
          type: string
    TurnRequest:
      type: object
      properties:
        playerId:
          type: string
        position:
          type: integer
          format: int32
    TurnResponse:
      type: object
      properties:
        gameOver:
          type: boolean
        winner:
          $ref: '#/components/schemas/Player'
        state:
          type: object
          additionalProperties:
            type: string
          